version: "3.9"

services:

  neo4j:
    image: neo4j
    volumes:
      - ./data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/gradvek1


  gradvek:
    image: davida26/gradvek2.0:latest
    ports:
      - "3000:3000"
      - "8080:8080"
    build:
      context: .